"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function IntakeForm(){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [fallback,setFallback]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());try{const r=await fetch("/api/people",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not start analysis");sessionStorage.setItem(`proxy:${data.id}`,JSON.stringify(data));router.push(`/run/${data.id}`)}catch(e){setError(e instanceof Error?e.message:"Something went wrong");setBusy(false)}}
 return <form className="intake" onSubmit={submit}><span className="eyebrow">Build your proxy</span><label>LinkedIn profile</label><input name="linkedinUrl" type="url" placeholder="https://linkedin.com/in/you" required/><label>Public Instagram</label><input name="instagramUrl" type="url" placeholder="https://instagram.com/you" required/><label>Interested in <span className="note">(optional)</span></label><input name="interestedIn" placeholder="Leave blank for preference-neutral matching"/>{fallback&&<><label>Profile text fallback</label><textarea name="fallbackText" placeholder="Paste public LinkedIn or Instagram profile text here…"/></>}<button type="button" className="note" style={{border:0,background:"none",cursor:"pointer",marginTop:14}} onClick={()=>setFallback(v=>!v)}>{fallback?"Hide":"Scraper blocked? Paste profile text instead"}</button><button className="button" disabled={busy}>{busy?"Reading the signals…":"Create my dating agent →"}</button>{error&&<div className="error">{error}</div>}<p className="note">Only the two links above are used. No sensitive traits are inferred.</p></form>
}
