import {generate} from "@/lib/llm/providers";import {evidenceCompleteProfileSchema} from "@/lib/schema";
const system="Use ONLY the supplied LinkedIn and Instagram data. Never infer sexual orientation, religion, health, or politics. Sparse data means lower confidence, never invention. Output valid JSON only with summary, career_stage, skills, hobbies, interests, values, communication_style, lifestyle, location, needs, looking_for, deal_breakers, confidence, and evidence. Evidence must contain at least one item for EACH of these fields: summary, career_stage, skills, hobbies, interests, values, communication_style, lifestyle, location, needs, looking_for, deal_breakers. Every evidence item is {field,claim,source,snippet}; source is exactly LinkedIn or Instagram and snippet is a short verbatim excerpt from the supplied data. If a field is unknown, state that in the field and cite the source gap without inventing.";
function normalize(value:unknown){const p=value as Record<string,unknown>;const strings=(v:unknown)=>Array.isArray(v)?v.map(String):v?[String(v)]:[];const text=(v:unknown,fallback="Not enough public information")=>Array.isArray(v)?v.join("; "):String(v||fallback),evidence=Array.isArray(p.evidence)?p.evidence.map((item)=>{const e=item as Record<string,unknown>;const raw=String(e.source||"").toLowerCase();return {field:String(e.field||"").toLowerCase(),claim:text(e.claim,"Public signal"),source:raw.includes("linkedin")?"LinkedIn" as const:"Instagram" as const,snippet:text(e.snippet,"")}}):[],unsupported=/\b(unknown|not enough|not present|no .* (listed|mentioned|expressed|information)|source gap)\b/i,supportedFields=new Set(evidence.filter(item=>!unsupported.test(`${item.claim} ${item.snippet}`)).map(item=>item.field)),evidenceConfidence=Math.min(.9,supportedFields.size/12),reported=Math.max(0,Math.min(1,Number(p.confidence)||0));return {...p,summary:text(p.summary),career_stage:text(p.career_stage),communication_style:text(p.communication_style),lifestyle:text(p.lifestyle),location:text(p.location),skills:strings(p.skills),hobbies:strings(p.hobbies),interests:strings(p.interests),values:strings(p.values),needs:strings(p.needs),deal_breakers:strings(p.deal_breakers),looking_for:text(p.looking_for),confidence:Math.max(reported,evidenceConfidence),evidence};}
function record(value:unknown){const unwrapped=Array.isArray(value)?value[0]:value;return unwrapped&&typeof unwrapped==="object"?unwrapped as Record<string,unknown>:{};}
function clip(value:unknown,max=700){return String(value||"").slice(0,max);}
function compactSources(sources:unknown){
  const value=sources&&typeof sources==="object"?sources as Record<string,unknown>:{},linkedin=record(value.linkedin),instagram=record(value.instagram),list=(input:unknown)=>Array.isArray(input)?input:[];
  const compactLinkedIn={
    full_name:linkedin.full_name,profile_headline:linkedin.profile_headline,description:clip(linkedin.description,1200),job_title:linkedin.job_title,
    industry_name:linkedin.industry_name||linkedin.industry,current_company_name:linkedin.current_company_name,location:linkedin.address||linkedin.location,
    skills:list(linkedin.skills).slice(0,20),
    experience:list(linkedin.experience).slice(0,6).map(item=>{const row=record(item);return {job_title:row.job_title,company_name:row.company_name,job_location:row.job_location,employment_type:row.employment_type,job_description:clip(row.job_description,600),company_description:clip(row.company_description,700)}}),
    featured:list(linkedin.featured).slice(0,6).map(item=>{const row=record(item);return {type:row.type,description:clip(row.description,900)}}),
    education:list(linkedin.education).slice(0,5),publication:list(linkedin.publication).slice(0,5),volunteering:list(linkedin.volunteering).slice(0,5),certification:list(linkedin.certification).slice(0,5),honors_and_awards:list(linkedin.honors_and_awards).slice(0,5),
  };
  const compactInstagram={
    fullName:instagram.fullName,username:instagram.username,biography:clip(instagram.biography,1200),verified:instagram.verified,businessCategoryName:instagram.businessCategoryName,externalUrl:instagram.externalUrl,postsCount:instagram.postsCount,followersCount:instagram.followersCount,
    latestPosts:list(instagram.latestPosts).slice(0,10).map(item=>{const row=record(item);return {caption:clip(row.caption,900),hashtags:list(row.hashtags).slice(0,15),timestamp:row.timestamp,locationName:row.locationName}}),
  };
  return JSON.stringify({linkedin:compactLinkedIn,instagram:compactInstagram});
}
export async function analyze(sources:unknown,retry=false){const content=compactSources(sources),instruction=retry?`A previous queued attempt returned invalid or incomplete JSON. Return valid JSON with all 12 evidence field labels exactly.\n${content}`:content,text=(await generate({system,messages:[{role:"user",content:instruction}]})).replace(/^```json\s*|\s*```$/g,"");return evidenceCompleteProfileSchema.parse(normalize(JSON.parse(text)));}
