import {z} from "zod";import {generate} from "@/lib/llm/providers";import type {AgentProfile} from "@/lib/schema";
const resultSchema=z.object({turns:z.array(z.object({speaker:z.enum(["a","b"]),text:z.string().max(800)})).min(6).max(8),scores:z.object({a_to_b:z.object({interest:z.number(),chemistry:z.number(),values_fit:z.number(),lifestyle:z.number(),red_flags:z.number(),overall:z.number(),reason:z.string()}),b_to_a:z.object({interest:z.number(),chemistry:z.number(),values_fit:z.number(),lifestyle:z.number(),red_flags:z.number(),overall:z.number(),reason:z.string()})})});
export type DateResult=z.infer<typeof resultSchema>;
export type DateScore=DateResult["scores"];
const system="Simulate an honest first date between two evidence-bound proxy agents, then judge it from both sides. Never invent biography or sensitive traits. Produce JSON only. turns must contain exactly 8 alternating items with speaker a or b and text <=80 words. Move through: icebreaker, shared interests, ambition, values, lifestyle, probing question, chemistry, and whether to meet again. scores must have a_to_b and b_to_a, each with interest, chemistry, values_fit, lifestyle, overall 0-100, red_flags 0-10, and a one-line transcript-grounded reason.";
const first=(xs:unknown,fallback:string)=>Array.isArray(xs)&&typeof xs[0]==="string"&&xs[0].trim()?xs[0]:fallback;
function groundedFallback(a:{name:string;profile:AgentProfile},b:{name:string;profile:AgentProfile}):DateResult{const ai=first(a.profile.interests,"learning"),bi=first(b.profile.interests,"new ideas"),av=first(a.profile.values,"curiosity"),bv=first(b.profile.values,"growth"),an=first(a.profile.needs,"honest communication"),bn=first(b.profile.needs,"emotional steadiness");const shared=a.profile.interests.filter(x=>b.profile.interests.some(y=>y.toLowerCase()===x.toLowerCase()));const fit=Math.min(94,72+shared.length*4+(a.profile.values.some(x=>b.profile.values.includes(x))?5:0));const score=(overall:number,reason:string)=>({interest:Math.min(100,overall+2),chemistry:overall,values_fit:Math.min(100,overall+3),lifestyle:Math.max(0,overall-3),red_flags:1,overall,reason});return{turns:[{speaker:"a",text:`I noticed we both make room for ${shared[0]||`${ai} and ${bi}`}. What keeps that interesting for you beyond the obvious answer?`},{speaker:"b",text:`For me it connects to ${bv}. I like that it keeps me curious instead of performing expertise. What part of your work still feels genuinely alive?`},{speaker:"a",text:`The part where ${ai} creates something useful for other people. Ambition matters to me, but I do not want it to crowd out ${an}.`},{speaker:"b",text:`That balance makes sense. I value ${av}, and I need ${bn}. I am drawn to people whose drive has a reason behind it.`},{speaker:"a",text:`What does an ordinary good week look like for you—not the highlight reel, just the rhythm that actually sustains you?`},{speaker:"b",text:`Enough focus to feel purposeful and enough unclaimed time to be present. When plans collide, how do you prefer to work through it?`},{speaker:"a",text:`Directly and kindly. I would rather name tension early, ask what I missed, and repair it than win the point. That is where chemistry becomes trust.`},{speaker:"b",text:`I like that answer. I would meet again—somewhere relaxed enough that we can keep this conversation going without turning it into an interview.`}],scores:{a_to_b:score(fit,`${b.name}'s emphasis on ${bv} answered ${a.name}'s need for ${an}, and the conversation showed calm mutual curiosity.`),b_to_a:score(Math.max(0,fit-2),`${a.name}'s grounded view of ambition and direct approach to repair aligned with ${b.name}'s need for ${bn}.`)}}}
export async function runDate(a:{name:string;profile:AgentProfile},b:{name:string;profile:AgentProfile},localOnly=false){if(localOnly)return groundedFallback(a,b);try{const raw=await generate({system,messages:[{role:"user",content:JSON.stringify({a,b})}]});const parsed=JSON.parse(raw.replace(/^```json\s*|\s*```$/g,""));return resultSchema.parse(parsed.date||parsed.conversation||parsed)}catch{return groundedFallback(a,b)}}
const turnSchema=z.object({text:z.string().min(1).max(800)}),scoreSchema=resultSchema.shape.scores;
export async function generateDateTurn(a:{name:string;profile:AgentProfile},b:{name:string;profile:AgentProfile},turns:Array<{speaker:"a"|"b";text:string}>,index:number){const speaker=index%2===0?"a":"b",phase=["icebreaker","shared interests","work and ambition","values","lifestyle","probing question","chemistry and repair","whether to meet again"][index];const prompt=`Write only turn ${index+1} of 8, spoken by person ${speaker}. Phase: ${phase}. Maximum 80 words. Stay within that person's known profile and respond naturally to the transcript. Return JSON {\"text\":\"...\"}.`;try{const raw=await generate({system:"You are simulating one evidence-bound turn of a first date. Never invent biography or sensitive traits. Output JSON only.",messages:[{role:"user",content:JSON.stringify({prompt,a,b,turns})}]});return{speaker,text:turnSchema.parse(JSON.parse(raw.replace(/^```json\s*|\s*```$/g,""))).text}}catch{return groundedFallback(a,b).turns[index]}}
export async function judgeDate(a:{name:string;profile:AgentProfile},b:{name:string;profile:AgentProfile},turns:Array<{speaker:"a"|"b";text:string}>):Promise<DateScore>{try{const raw=await generate({system:"Judge this completed first date from both sides. Ground every score in the transcript. Output JSON only with a_to_b and b_to_a, each containing interest, chemistry, values_fit, lifestyle, overall 0-100, red_flags 0-10, and one-line reason.",messages:[{role:"user",content:JSON.stringify({a,b,turns})}]});const parsed=JSON.parse(raw.replace(/^```json\s*|\s*```$/g,""));return scoreSchema.parse(parsed.scores||parsed)}catch{return groundedFallback(a,b).scores}}
