import {loadEnvConfig} from "@next/env";import {readFile,writeFile,mkdir} from "node:fs/promises";import path from "node:path";import {embed,selectPairs} from "../lib/rank/pairs";import {runDate} from "../lib/agents/date";import {analyze} from "../lib/agents/analyst";import {scrapeBoth} from "../lib/scrape/apify";import {finalScore} from "../lib/rank/score";import type {DemoRun,RunPerson,RunDate,RunRanking} from "../lib/types";
async function main(){loadEnvConfig(process.cwd());const root=process.cwd(),stateDir=path.join(root,".data","demo");await mkdir(stateDir,{recursive:true});
const rows=(await readFile(path.join(root,"db","seed_people.csv"),"utf8")).trim().split(/\r?\n/).slice(1).map((line,i)=>{const [name,linkedin,instagram]=line.split(",");return{id:`person-${i+1}`,name,linkedin,instagram}});
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function profile(row:typeof rows[number]):Promise<RunPerson>{const file=path.join(stateDir,`${row.id}.json`);try{return JSON.parse(await readFile(file,"utf8"))}catch{}const sources=await scrapeBoth(row.linkedin,row.instagram),analyzed=await analyze(sources),embedding=await embed([analyzed.needs,analyzed.values,analyzed.interests,analyzed.lifestyle].flat().join(" | "));const value={...row,profile:analyzed,embedding};await writeFile(file,JSON.stringify(value),"utf8");console.log(`profile ${row.id} ${row.name}`);return value}
const people:RunPerson[]=[];for(const row of rows){try{people.push(await profile(row))}catch(e){console.error(String(e))}await sleep(1200)}if(people.length<25)throw new Error(`Only ${people.length} profiles completed; need 25`);
const vectors=Object.fromEntries(people.map(p=>[p.id,p.embedding]));const pairs=selectPairs(people.map(p=>p.id),vectors,6);console.log(`${pairs.length} deduplicated dates selected`);const dates:RunDate[]=[];let cursor=0;
async function dateWorker(){while(true){const i=cursor++;if(i>=pairs.length)return;const pair=pairs[i],id=`${pair.aId}--${pair.bId}`,file=path.join(stateDir,`date-${id}.json`);try{const cached=JSON.parse(await readFile(file,"utf8"));if(cached.result?.turns?.length===12&&cached.result?.reflections){dates.push(cached);continue}}catch{}const a=people.find(p=>p.id===pair.aId)!,b=people.find(p=>p.id===pair.bId)!;try{const result=await runDate(a,b,true),value={id,...pair,result};dates.push(value);await writeFile(file,JSON.stringify(value),"utf8");console.log(`date ${i+1}/${pairs.length} ${a.name} x ${b.name}`)}catch(e){console.error(`date ${id}: ${String(e)}`)}await sleep(50)}}
await Promise.all([dateWorker(),dateWorker(),dateWorker()]);
const rankings:RunRanking[]=[];for(const p of people){const list=dates.filter(d=>d.aId===p.id||d.bId===p.id).map(d=>{const isA=d.aId===p.id,s=d.result.scores,self=isA?s.a_to_b:s.b_to_a,mutual=isA?s.b_to_a:s.a_to_b;return{personId:p.id,matchId:isA?d.bId:d.aId,score:finalScore(self.overall,mutual.overall,d.similarity,self.red_flags,mutual.red_flags),reason:self.reason,dateId:d.id}}).sort((a,b)=>b.score-a.score);list.forEach((x,i)=>rankings.push({...x,rank:i+1}))}
if(dates.length<90)throw new Error(`Only ${dates.length} dates completed; need at least 90`);const run:DemoRun={id:"demo",createdAt:new Date().toISOString(),status:"complete",people,dates,rankings};await writeFile(path.join(root,"db","demo-run.json"),JSON.stringify(run),"utf8");console.log(`complete: ${people.length} people, ${dates.length} dates, ${rankings.length} rankings`);}
main().catch(error=>{console.error(error);process.exitCode=1});
